version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

    groups:
      non-major-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

    ignore:
      - dependency-name: "@klurigo/common"
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"

    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

    groups:
      non-major-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
