version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
    schedule:
      interval: "weekly"

    groups:
      non-major-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

    ignore:
      - dependency-name: "@klurigo/common"

    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

    groups:
      non-major-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
