#!/usr/bin/env bash

#
# Dump, migrate, and restore Klurigo MongoDB data.
#
# The script performs the following steps:
#
#   1. Creates a dated dump of the production database.
#   2. Removes any existing migrated output.
#   3. Runs the Klurigo MongoDB migrator against the production dump.
#   4. Restores the migrated data to the local database.
#   5. Restores the migrated data to the beta database.
#   6. Restores the migrated data to the production database.
#
# Every step requires explicit confirmation before it is executed. Entering
# anything other than "y" or "Y" aborts the script.
#
# WARNING:
#
# The restore steps use `mongorestore --drop`. Existing collections in the
# target database are dropped before the migrated data is restored.
#
# Requirements:
#
#   - Bash
#   - MongoDB Database Tools:
#       - mongodump
#       - mongorestore
#   - Node.js
#   - Yarn
#   - The Klurigo project and its `mongodb-migrator` workspace
#
# Required environment variables:
#
#   KLURIGO_DUMP_ROOT_DIR
#     Directory in which production dumps and migrated output are stored.
#
#   KLURIGO_PROJECT_DIR
#     Path to the Klurigo project repository.
#
#   KLURIGO_MONGODB_HOST
#     Hostname of the remote MongoDB server.
#
#   KLURIGO_MONGODB_PORT
#     Port of the remote MongoDB server.
#
#   KLURIGO_PROD_MONGODB_DB
#     Name of the production MongoDB database.
#
#   KLURIGO_BETA_MONGODB_DB
#     Name of the beta MongoDB database.
#
#   KLURIGO_PROD_MONGODB_USERNAME
#     Username used to access the production database.
#
#   KLURIGO_PROD_MONGODB_PASSWORD
#     Password used to access the production database.
#
#   KLURIGO_BETA_MONGODB_USERNAME
#     Username used to access the beta database.
#
#   KLURIGO_BETA_MONGODB_PASSWORD
#     Password used to access the beta database.
#
# Example configuration:
#
#   export KLURIGO_DUMP_ROOT_DIR="/path/to/klurigo/dumps"
#   export KLURIGO_PROJECT_DIR="/path/to/klurigo"
#   export KLURIGO_MONGODB_HOST="mongodb.example.com"
#   export KLURIGO_MONGODB_PORT="27017"
#   export KLURIGO_PROD_MONGODB_DB="klurigo_prod"
#   export KLURIGO_BETA_MONGODB_DB="klurigo_beta"
#   export KLURIGO_PROD_MONGODB_USERNAME="..."
#   export KLURIGO_PROD_MONGODB_PASSWORD="..."
#   export KLURIGO_BETA_MONGODB_USERNAME="..."
#   export KLURIGO_BETA_MONGODB_PASSWORD="..."
#
# Usage:
#
#   ./migrate-mongodb-data
#

set -e

CURRENT_DATE=$(date +%Y-%m-%d)

# Store each production dump in a directory named after the current date.
PROD_DUMP_DIR="$KLURIGO_DUMP_ROOT_DIR/klurigo_prod-$CURRENT_DATE"

# Store the output generated by mongodb-migrator in a shared directory.
MIGRATION_OUT_DIR="$KLURIGO_DUMP_ROOT_DIR/klurigo_migrated"

# MongoDB connection URI for the local Klurigo database.
#
# shellcheck disable=SC2034
MONGODB_KLURIGO_LOCAL_URI="mongodb://127.0.0.1:27017/klurigo_service"

# MongoDB connection URI for the production Klurigo database.
#
# shellcheck disable=SC2034
MONGODB_KLURIGO_PROD_URI="mongodb://$KLURIGO_PROD_MONGODB_USERNAME:$KLURIGO_PROD_MONGODB_PASSWORD@$KLURIGO_MONGODB_HOST:$KLURIGO_MONGODB_PORT/$KLURIGO_PROD_MONGODB_DB"

# MongoDB connection URI for the beta Klurigo database.
#
# shellcheck disable=SC2034
MONGODB_KLURIGO_BETA_URI="mongodb://$KLURIGO_BETA_MONGODB_USERNAME:$KLURIGO_BETA_MONGODB_PASSWORD@$KLURIGO_MONGODB_HOST:$KLURIGO_MONGODB_PORT/$KLURIGO_BETA_MONGODB_DB"

#
# Ask the user to confirm a potentially destructive operation.
#
# The operation continues only when the user explicitly enters "y" or "Y".
# Any other response aborts the script.
#
# Arguments:
#   $1 - Confirmation message displayed to the user.
#
confirm_or_exit() {
  read -r -p "$1 [Y/n]: " response

  if [[ ! "$response" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
  fi
}

# Step 1:
# Create a dated dump of the current production database.
confirm_or_exit "Step 1: Dump production database to $PROD_DUMP_DIR?"
mongodump \
  --uri="$MONGODB_KLURIGO_PROD_URI" \
  --out="$PROD_DUMP_DIR"

# Step 2:
# Remove output left by a previous migration.
confirm_or_exit "Step 2: Remove existing migration output directory $MIGRATION_OUT_DIR?"
rm -rf "$MIGRATION_OUT_DIR"

# Step 3:
# Run mongodb-migrator against the dumped production database.
#
# mongodump stores the database contents under:
#
#   <dump directory>/<database name>
#
# The migrator writes the transformed database dump to MIGRATION_OUT_DIR.
confirm_or_exit "Step 3: Run mongodb-migrator?"
cd "$KLURIGO_PROJECT_DIR"

yarn workspace mongodb-migrator run start \
  --inputDir "$PROD_DUMP_DIR/$KLURIGO_PROD_MONGODB_DB" \
  --outputDir "$MIGRATION_OUT_DIR"

# Step 4:
# Replace the local database with the migrated data.
confirm_or_exit "Step 4: Restore LOCAL database?"
mongorestore \
  --uri="$MONGODB_KLURIGO_LOCAL_URI" \
  --drop \
  "$MIGRATION_OUT_DIR"

# Step 5:
# Replace the beta database with the migrated data.
confirm_or_exit "Step 5: Restore BETA database?"
mongorestore \
  --uri="$MONGODB_KLURIGO_BETA_URI" \
  --drop \
  "$MIGRATION_OUT_DIR"

# Step 6:
# Replace the production database with the migrated data.
confirm_or_exit "Step 6: Restore PROD database?"
mongorestore \
  --uri="$MONGODB_KLURIGO_PROD_URI" \
  --drop \
  "$MIGRATION_OUT_DIR"

echo "Done."
